### ISSUE TITLE
Corfu strange cutoff

### ISSUE THREAD

**Issue by cheerio-pixel** [LuigiPiucco/nerd-icons-corfu#11]
Only when I'm using icons the completion popup seems to have a strange margin on the bottom, like the icons seem to add a padding corfu isn't aware.
![image](https://github.com/LuigiPiucco/nerd-icons-corfu/assets/74797568/9c25f1c8-0fb9-43b8-96ca-4b48a1408896)

**Comment by LuigiPiucco** [comment]
Just to clarify, that blue stripe at the bottom is another candidate, correct? As in, you moved the selection to the last one, and it's cut off. I ask because this has come up before with another package, it's part of why this one exists. If not, and that's actually a margin that's added somehow, the troubleshooting changes a lot. I'll try to reproduce and possibly fix while I wait for your response.

Edit: I just noticed it's suggesting `company-mode` symbols, which usually means you have `company-mode` loaded into you Emacs session. Check if it is active (what's the value of the variable `company-mode-major-mode` in that buffer?), because `corfu` does not support working alongside company, and this package is also not usable with it.

**Comment by cheerio-pixel** [comment]
Yes, it's a selection. Now, for some reason the problem has solved itself and the company-mode-major-mode evaluates to nil in any mode. It's suggesting me those symbols because it's a dependency of another package.

**Comment by LuigiPiucco** [comment]
Ok. If it's fixed, I'll close. Feel free to reopen if needed or if it comes back.
