### ISSUE TITLE
Icon spacing broken in the terminal

### ISSUE THREAD

**Issue by mhcerri** [LuigiPiucco/nerd-icons-corfu#14]
Commit 43d54dd37071 broke the spacing for the icons in the terminal:

![image](https://github.com/user-attachments/assets/bde6d4ab-8418-41f5-81f3-9c21510bbfa5)

If I change the space width back to 1 it looks normal again:

![image](https://github.com/user-attachments/assets/a9c80a3f-2a23-41ee-bab9-a3f62212b008)

Is there any specific reason for 0.5 for the width? Maybe we should have a configuration for that or a different value for graphical vs terminal environments.

Do you have any preference on how to handle that? Thank you!

**Comment by LuigiPiucco** [comment]
Hi, yes, there is: Corfu actually requires the icon returned by the margin formatter to have a whole graphical width equivalent to the "expected" width of the string it returns. So since we return a three character string (`space` `icon` `space`), it must be 3 times the default width of a character. Otherwise, characters get cutoff on the opposite side of the popup.

However, nerd-icons are double-width in graphical displays (they occupy twice the default width, or two characters worth of space). To make the sum equal three, the spaces must be half-width. I'm not sure about their size in terminal though.

Now, default Corfu only supports graphical displays, so technically terminal is an out-of-scope feature (even though I mention supporting it in the README, that was an oversight), but I'll experiment with it later (I'm currently away from my computer). Most likely it won't be fully fixable though.

Meanwhile, can you test if there is cutoff on the right in terminal?

Note: at the time of the commit you linked, it was an arbitrary choice, but later I discovered the above requirement. That's why the commit doesn't mention it.

**Comment by mhcerri** [comment]
Hey! Thanks for checking that!

> Now, default Corfu only supports graphical displays, so technically terminal is an out-of-scope feature 

This is technically true, corfu doesn't support terminal out of the box but its README recommends corfu-terminal for that.

In my config, all I had to do to have corfu working in the terminal was to add that to my config:

```elisp
(use-package corfu-terminal
  :if (not (display-graphic-p))
  :config
  (corfu-terminal-mode 1))
```
> Meanwhile, can you test if there is cutoff on the right in terminal?

In the example I posted above `testcover-this-defun` is already expanding the width of the completion box and it doesn't seems it's cutting it off in the right side in either cases. 

I decided to test the same two cases I posted above but now using emacs in graphical mode. By default (with `0.5` for space) the result looks better than in the terminal but it still looks a bit off:


![image](https://github.com/user-attachments/assets/fe6f0e54-51dc-4087-b3f5-8a5d7ead21eb)

Please note how the icon for `ert-deftest`overlaps with the text.

When I set the space back to one, the icon spacing looks way better and it doesn't seem it's cutting the text off in the right side (please check `testcover-this-defun` in the image):

![image](https://github.com/user-attachments/assets/846cf52d-e766-40ac-b6a5-e8d46bb26a30)

I'm wondering if that difference might be related to the emacs version we both are using (I'm using version 29.0.92) or to any other external factors.

Thank you!

**Comment by LuigiPiucco** [comment]
I've done some testing, and found that the major factor seems to be the terminal used. I tested Alacritty and Konsole, and they displayed things differently when using non-integer spaces. I use Emacs HEAD, so there may also be some version differences, since it seems from your screenshots that your graphical Emacs is treating the glyphs like terminals do: they align the right-side of the glyph with the beginning of the character column, and ignore the size of the actual drawing, causing it to clip into the next character when it is too big. This also has the side-effect that the glyph is not centered.

As a best effort solution, I'll push a change that removes the first space on terminal. The string will therefore be of length 2 which, due to the way terminals draw (as described above), seems to look OK here (the drawn part of the icons is slightly smaller than the worth of 2 characters, so there is still some spacing). Please close once you've tested if it is enough.

**Comment by mhcerri** [comment]
Thanks a lot! That fixes the problem for me.
