### ISSUE TITLE
a difference between this project and kind-icon

### ISSUE THREAD

**Issue by dsh2dsh** [LuigiPiucco/nerd-icons-corfu#3]
Hi,

could you describe what's difference between this project and https://github.com/jdtsmith/kind-icon ? I see they both add icons into corfu dropdown.

Thanks.

**Comment by LuigiPiucco** [comment]
Sure! Yes, they both add icons, but the goals and methods are slightly different. First, though `kind-icon` focuses on corfu, it's more-or-less agnostic, you can use it for `company-mode`, for instance. This package is more limited in regard to scope. Second, `kind-icon` uses [svg-lib](https://github.com/rougier/svg-lib) under the hood, and it actually draws images for the icons in graphical displays. This causes some overhead and does not work on terminal (where it falls back to plain text). `nerd-icons-corfu` uses [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el) only, which is an icon fonts provider. So the icons you're seeing when using this are actually Unicode text mapped with a special font, not images. This is more portable and lightweight. Third, `kind-icon` [can also be configured to use `nerd-icons.el`](https://github.com/rainstormstudio/nerd-icons.el#use-nerd-icons-with-corfu), but that requires significant manual intervention and is a bit of overkill, since you'd leave its image drawing capabilities underutilized. Here we add Nerd Icons support to Corfu and only that. None of this is to say `kind-icon` is bad or worse, it's really a matter of taste, since its icons are a bit more elaborate.

I hope this was enough, but feel free to ask again if needed, or close if not.

**Comment by nsemrau** [comment]
@LuigiPiucco Putting a gist of what you wrote here as a section into the README file ("Difference between kind-icon and nerd-icons-corfu") would IMHO be helpful and informative towards prospective users.

**Comment by dsh2dsh** [comment]
@LuigiPiucco thank you very much for your excellent explanation. I agree with @nsemrau it would be very helpful to see it in the README.

**Comment by LuigiPiucco** [comment]
I added the explanation, so I'll close this as completed.
