### ISSUE TITLE
A delay on first open of corfu drop-down list of completions

### ISSUE THREAD

**Issue by dsh2dsh** [LuigiPiucco/nerd-icons-corfu#9]
Hi,

After fresh emacs restart, I feel delay on first TAB. I see empty corfu's dropdown and after some delay it fills with content. After that it works fast without any delay. May be do I need to preload nerd font somehow? Here my config:
```
(use-package nerd-icons-corfu
  :after corfu
  :config
  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
```

**Comment by LuigiPiucco** [comment]
Hey, sorry for the delay. First, I ask for confirmation this still happens. Nothing was changed here that should fix it, but just in case.
About preloading, I don't think that should be needed. To my understanding, Nerd Fonts are fonts like regular text ones, just bigger due to the extra glyph data. Perhaps @rainstormstudio, author of the underlying [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el), might say otherwise?

My main guess here is that there's a gap between loading Corfu into Emacs and loading nerd-icons-corfu. I'm not a specialist in use-package, but I see you've configured this package as a formatter in the `:config` section, which happens _after_ it is loaded. It's still being loaded because Corfu loads and `:after` makes sure we follow, but if you wanted on-demand loading with autoloads for instance, this would not work. Try changing `:config` to `:init` (happens as soon as viable on Emacs start), or moving the `add-to-list` line to corfu's use-package.

I also recommend not using `:after`, it loads the entire package immediately, using autoloads is generally better. This way, the package loads on the first use of registered commands. Here's an example:

```emacs-lisp
(use-package corfu
  ;; ...
  :config
  ;; ...
  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

(use-package nerd-icons-corfu
  ;; Register autoloads for the following commands.
  :commands nerd-icons-corfu-formatter)
```

**Comment by dsh2dsh** [comment]
> First, I ask for confirmation this still happens. Nothing was changed here that should fix it, but just in case.

I installed `nerd-icons-corfu` back and tried my configuration from my message and it works now fine, without any delay. May be something changed somewhere. Sorry for false report, I'm closing this issue. And thanks.
